export function buildModernTemplate(data, isPreview, langName) {
  const { name, business, designation, phone, email, address, services, tagline, about, faqs, testimonials, theme, images } = data;

  const translations = {
    "English": {
      myBusiness: "My Business",
      professionalServices: "Professional Services",
      callUs: "Call Us",
      emailUs: "Email Us",
      location: "Location",
      premiumQuality: "Premium Quality",
      guaranteedExp: "Guaranteed Experience",
      whatWeDo: "What We Do",
      expertise: "Expertise & Services",
      generatedBy: "Generated by Yuktha",
      getInTouch: "Get in Touch",
      allRights: "All Rights Reserved",
      aboutUs: "About Us",
      faqTitle: "Frequently Asked Questions",
      testimonialsTitle: "What Our Clients Say",
      galleryTitle: "Our Work",
      home: "Home",
      servicesNav: "Services",
      contactNav: "Contact"
    },
    "Tamil": {
      myBusiness: "என் வணிகம்",
      professionalServices: "தொழில்முறை சேவைகள்",
      callUs: "அழைக்க",
      emailUs: "மின்னஞ்சல்",
      location: "இருப்பிடம்",
      premiumQuality: "உயர்தரமான தரம்",
      guaranteedExp: "உத்தரவாதமான அனுபவம்",
      whatWeDo: "நாங்கள் செய்வது",
      expertise: "நிபுணத்துவம் மற்றும் சேவைகள்",
      generatedBy: "யுக்தா மூலம் உருவாக்கப்பட்டது",
      getInTouch: "தொடர்புகொள்ளுங்கள்",
      allRights: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை",
      aboutUs: "எங்களை பற்றி",
      faqTitle: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
      testimonialsTitle: "வாடிக்கையாளர் மதிப்புரைகள்",
      galleryTitle: "எங்கள் படைப்புகள்",
      home: "முகப்பு",
      servicesNav: "சேவைகள்",
      contactNav: "தொடர்பு"
    },
    "Hindi": {
      myBusiness: "मेरा व्यापार",
      professionalServices: "पेशेवर सेवाएं",
      callUs: "हमें कॉल करें",
      emailUs: "ईमेल करें",
      location: "स्थान",
      premiumQuality: "प्रीमियम गुणवत्ता",
      guaranteedExp: "गारंटीशुदा अनुभव",
      whatWeDo: "हम क्या करते हैं",
      expertise: "विशेषज्ञता और सेवाएं",
      generatedBy: "युक्ता द्वारा निर्मित",
      getInTouch: "संपर्क करें",
      allRights: "सर्वाधिकार सुरक्षित",
      aboutUs: "हमारे बारे में",
      faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
      testimonialsTitle: "ग्राहक समीक्षा",
      galleryTitle: "हमारा काम",
      home: "होम",
      servicesNav: "सेवाएं",
      contactNav: "संपर्क"
    },
    "Telugu": {
      myBusiness: "నా వ్యాపారం",
      professionalServices: "వృత్తిపరమైన సేవలు",
      callUs: "మాకు కాల్ చేయండి",
      emailUs: "ఈమెయిల్ చేయండి",
      location: "స్థానం",
      premiumQuality: "ప్రీమియం నాణ్యత",
      guaranteedExp: "హామీ బడిన అనుభవం",
      whatWeDo: "మేము ఏమి చేస్తాము",
      expertise: "నైపుణ్యం మరియు సేవలు",
      generatedBy: "యుక్త ద్వారా సృష్టించబడింది",
      getInTouch: "మమ్మల్ని సంప్రదించండి",
      allRights: "సర్వ హక్కులూ ప్రత్యేకించబడినవి",
      aboutUs: "మా గురించి",
      faqTitle: "తరచుగా అడిగే ప్రశ్నలు",
      testimonialsTitle: "కస్టమర్ అభిప్రాయాలు",
      galleryTitle: "మా పని",
      home: "హోమ్",
      servicesNav: "సేవలు",
      contactNav: "సంప్రదించండి"
    },
    "Malayalam": {
      myBusiness: "എന്റെ ബിസിനസ്സ്",
      professionalServices: "പ്രൊഫഷണൽ സേവനങ്ങൾ",
      callUs: "ഞങ്ങളെ വിളിക്കുക",
      emailUs: "ഇമെയിൽ ചെയ്യുക",
      location: "സ്ഥാനം",
      premiumQuality: "പ്രീമിയം നിലവാരം",
      guaranteedExp: "ഉറപ്പായ അനുഭവം",
      whatWeDo: "ഞങ്ങൾ ചെയ്യുന്നത്",
      expertise: "വൈദഗ്ധ്യവും സേവനങ്ങളും",
      generatedBy: "യുക്ത നിർമ്മിച്ചത്",
      getInTouch: "ബന്ധപ്പെടുക",
      allRights: "എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം",
      aboutUs: "ഞങ്ങളെക്കുറിച്ച്",
      faqTitle: "പതിവായി ചോദിക്കുന്ന ചോദ്യങ്ങൾ",
      testimonialsTitle: "ഉപഭോക്തൃ അഭിപ്രായങ്ങൾ",
      galleryTitle: "ഞങ്ങളുടെ പ്രവർത്തനം",
      home: "ഹോം",
      servicesNav: "സേവനങ്ങൾ",
      contactNav: "ബന്ധപ്പെടുക"
    },
    "Kannada": {
      myBusiness: "ನನ್ನ ವ್ಯಾಪಾರ",
      professionalServices: "ವೃತ್ತಿಪರ ಸೇವೆಗಳು",
      callUs: "ನಮ್ಮನ್ನು ಕರೆ ಮಾಡಿ",
      emailUs: "ಇಮೇಲ್ ಮಾಡಿ",
      location: "ಸ್ಥಳ",
      premiumQuality: "ಉತ್ತಮ ಗುಣಮಟ್ಟ",
      guaranteedExp: "ಖಾತರಿಯ ಅನುಭವ",
      whatWeDo: "ನಾವು ಮಾಡುವುದು",
      expertise: "ಪರಿಣತಿ ಮತ್ತು ಸೇವೆಗಳು",
      generatedBy: "ಯುಕ್ತಾ ಮೂಲಕ ರಚಿಸಲಾಗಿದೆ",
      getInTouch: "ಸಂಪರ್ಕಿಸಿ",
      allRights: "ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ",
      aboutUs: "ನಮ್ಮ ಬಗ್ಗೆ",
      faqTitle: "ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
      testimonialsTitle: "ಗ್ರಾಹಕರ ವಿಮರ್ಶೆಗಳು",
      galleryTitle: "ನಮ್ಮ ಕೆಲಸ",
      home: "ಹೋಮ್",
      servicesNav: "ಸೇವೆಗಳು",
      contactNav: "ಸಂಪರ್ಕಿಸಿ"
    },
    "Bengali": {
      myBusiness: "আমার ব্যবসা",
      professionalServices: "পেশাদার পরিষেবা",
      callUs: "আমাদের কল করুন",
      emailUs: "ইমেল করুন",
      location: "অবস্থান",
      premiumQuality: "প্রিমিয়াম গুণমান",
      guaranteedExp: "নিশ্চিত অভিজ্ঞতা",
      whatWeDo: "আমরা যা করি",
      expertise: "দক্ষতা এবং পরিষেবা",
      generatedBy: "যুক্তা দ্বারা তৈরি",
      getInTouch: "যোগাযোগ করুন",
      allRights: "সমস্ত অধিকার সংরক্ষিত",
      aboutUs: "আমাদের সম্পর্কে",
      faqTitle: "সাধারণ প্রশ্ন জিজ্ঞাসা",
      testimonialsTitle: "গ্রাহক পর্যালোচনা",
      galleryTitle: "আমাদের কাজ",
      home: "হোম",
      servicesNav: "পরিষেবা",
      contactNav: "যোগাযোগ"
    }
  };

  const tl = translations[isPreview ? langName : "English"] || translations["English"];

  // Add fallbacks
  const displayName = name || business || tl.myBusiness;
  const displayBusiness = business || tl.professionalServices;
  const primaryBrandColor = theme?.primaryColor || '#4f46e5';
  
  const phoneLink = phone ? `tel:${phone.replace(/[^0-9+]/g, '')}` : "#";
  const emailLink = email ? `mailto:${email}` : "#";
  const waLink = phone ? `https://wa.me/${phone.replace(/[^0-9+]/g, '')}` : "#";

  // Generate a deterministic "effect seed" from business name for unique backgrounds
  const seed = (displayName + displayBusiness).split('').reduce((a, c) => a + c.charCodeAt(0), 0);
  const effectType = seed % 4; // 0=blobs, 1=particles, 2=geometric, 3=waves

  // Create highly unique identifier per site combining multiple details
  const siteUniqueStr = displayName + displayBusiness + (about || '') + (phone || '') + (tagline || '');
  const uniqueSeed = siteUniqueStr.split('').reduce((a, c) => a + c.charCodeAt(0), 0);


  // Build background effect CSS based on effectType
  const bgEffects = [
    // Effect 0: Floating gradient blobs
    `
    .bg-effect::before, .bg-effect::after {
      content: ''; position: fixed; border-radius: 50%; pointer-events: none; z-index: 0; filter: blur(80px); opacity: 0.10;
    }
    .bg-effect::before {
      width: 500px; height: 500px; top: -100px; right: -100px;
      background: radial-gradient(circle, var(--primary-color), transparent 70%);
      animation: blobFloat1 20s ease-in-out infinite;
    }
    .bg-effect::after {
      width: 400px; height: 400px; bottom: -50px; left: -50px;
      background: radial-gradient(circle, #a855f7, transparent 70%);
      animation: blobFloat2 25s ease-in-out infinite;
    }
    @keyframes blobFloat1 { 0%,100%{transform:translate(0,0) scale(1)} 50%{transform:translate(-80px,60px) scale(1.15)} }
    @keyframes blobFloat2 { 0%,100%{transform:translate(0,0) scale(1)} 50%{transform:translate(60px,-80px) scale(1.2)} }
    `,
    // Effect 1: CSS dot particles
    `
    .bg-effect { position: relative; }
    .bg-effect::before {
      content: ''; position: fixed; inset: 0; z-index: 0; pointer-events: none;
      background-image: radial-gradient(circle, var(--primary-color) 1px, transparent 1px);
      background-size: 40px 40px; opacity: 0.04;
      animation: particleDrift 30s linear infinite;
    }
    @keyframes particleDrift { 0%{background-position:0 0} 100%{background-position:40px 40px} }
    `,
    // Effect 2: Geometric diagonal stripes
    `
    .bg-effect::before {
      content: ''; position: fixed; inset: 0; z-index: 0; pointer-events: none; opacity: 0.025;
      background: repeating-linear-gradient(
        -45deg, var(--primary-color), var(--primary-color) 1px, transparent 1px, transparent 50px
      );
    }
    `,
    // Effect 3: Animated wave at section borders
    `
    .bg-effect::before {
      content: ''; position: fixed; bottom: 0; left: 0; width: 200%; height: 200px; z-index: 0; pointer-events: none; opacity: 0.04;
      background: repeat-x url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1440 320'%3E%3Cpath fill='${encodeURIComponent(primaryBrandColor)}' d='M0,224L60,213.3C120,203,240,181,360,181.3C480,181,600,203,720,213.3C840,224,960,224,1080,208C1200,192,1320,160,1380,144L1440,128L1440,320L0,320Z'/%3E%3C/svg%3E");
      background-size: 1440px 320px;
      animation: waveSlide 15s linear infinite;
    }
    @keyframes waveSlide { 0%{transform:translateX(0)} 100%{transform:translateX(-50%)} }
    `
  ][effectType];

  // Build nav items – only for real content sections
  const navItems = [];
  navItems.push({ label: tl.home, href: '#home' });
  if (about) navItems.push({ label: tl.aboutUs, href: '#about' });
  if (services && services.length > 0) navItems.push({ label: tl.servicesNav, href: '#services' });
  if (phone || email || address) navItems.push({ label: tl.contactNav, href: '#contact' });

  const navHTML = navItems.map(n => `<a href="${n.href}" class="nav-link">${n.label}</a>`).join('');

  // Generate relevant image URLs using loremflickr (keyword-based, content-relevant)
  const getImageUrl = (keyword, index) => {
    const cleanKeyword = encodeURIComponent((keyword || 'business').trim().replace(/\s+/g, ','));
    // Combine site seed with index to guarantee unique images per session per keyword
    const lockId = Math.abs(seed + index * 137);
    return `https://loremflickr.com/800/600/${cleanKeyword}?lock=${lockId}`;
  };

  return `<!DOCTYPE html>
<html lang="${isPreview ? 'en' : 'en'}" class="scroll-smooth">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${displayName} - ${displayBusiness}</title>
    <script src="https://cdn.tailwindcss.com"><\/script>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        :root {
            --primary-color: ${primaryBrandColor};
        }
    
        body { font-family: 'Plus Jakarta Sans', sans-serif; background-color: #f8fafc; overflow-x: hidden; }
        
        /* Sticky Navbar */
        .site-nav {
            position: fixed; top: 0; left: 0; right: 0; z-index: 100;
            background: rgba(2, 6, 23, 0.85); backdrop-filter: blur(16px); -webkit-backdrop-filter: blur(16px);
            border-bottom: 1px solid rgba(255,255,255,0.08);
            transition: all 0.3s ease;
        }
        .site-nav.scrolled { background: rgba(2, 6, 23, 0.95); box-shadow: 0 4px 30px rgba(0,0,0,0.3); }
        .nav-inner { max-width: 1200px; margin: 0 auto; padding: 0 24px; display: flex; align-items: center; justify-content: space-between; height: 64px; }
        .nav-brand { font-weight: 800; font-size: 1.25rem; color: white; text-decoration: none; letter-spacing: -0.02em; }
        .nav-links { display: flex; gap: 8px; align-items: center; }
        .nav-link {
            color: rgba(255,255,255,0.7); text-decoration: none; font-size: 0.875rem; font-weight: 500;
            padding: 8px 16px; border-radius: 9999px; transition: all 0.25s ease;
        }
        .nav-link:hover, .nav-link.active { color: white; background: rgba(255,255,255,0.1); }
        .nav-hamburger { display: none; background: none; border: none; color: white; font-size: 1.5rem; cursor: pointer; }
        @media (max-width: 768px) {
            .nav-hamburger { display: block; }
            .nav-links {
                display: none; position: absolute; top: 64px; left: 0; right: 0;
                background: rgba(2, 6, 23, 0.95); backdrop-filter: blur(16px);
                flex-direction: column; padding: 16px; gap: 4px;
                border-bottom: 1px solid rgba(255,255,255,0.08);
            }
            .nav-links.open { display: flex; }
            .nav-link { width: 100%; text-align: center; padding: 12px 16px; }
        }

        /* Dynamic Hero Background */
        .hero-gradient {
            background: linear-gradient(-45deg, #020617, #0f172a, var(--primary-color), #0f172a);
            background-size: 400% 400%;
            animation: gradientBG 15s ease infinite;
            position: relative;
        }
        @keyframes gradientBG {
            0% { background-position: 0% 50%; }
            50% { background-position: 100% 50%; }
            100% { background-position: 0% 50%; }
        }
        
        /* Premium Glassmorphism */
        .glass-panel {
            background: rgba(255, 255, 255, 0.03);
            backdrop-filter: blur(16px);
            -webkit-backdrop-filter: blur(16px);
            border: 1px solid rgba(255, 255, 255, 0.05);
            box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
        }
        
        .bento-card {
            background: #ffffff;
            transition: all 0.4s cubic-bezier(0.16, 1, 0.3, 1);
            border: 1px solid rgba(226, 232, 240, 0.8);
        }
        .bento-card:hover {
            transform: translateY(-5px) scale(1.01);
            box-shadow: 0 20px 40px -10px rgba(79, 70, 229, 0.15);
            border-color: var(--primary-color);
        }

        .icon-gradient {
            background: linear-gradient(135deg, var(--primary-color), #a855f7);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        /* Subtle Reveal Animations */
        .animate-fade-in-up {
            animation: fadeInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) both;
        }
        .delay-100 { animation-delay: 0.1s; }
        .delay-200 { animation-delay: 0.2s; }
        .delay-300 { animation-delay: 0.3s; }
        @keyframes fadeInUp {
            from { opacity: 0; transform: translateY(30px); }
            to { opacity: 1; transform: translateY(0); }
        }

        /* Dynamic primary button */
        .btn-primary {
            background: linear-gradient(135deg, var(--primary-color), #7c3aed);
            transition: all 0.3s ease;
            position: relative;
            overflow: hidden;
            z-index: 1;
        }
        .btn-primary::before {
            content: '';
            position: absolute;
            top: 0; left: 0; right: 0; bottom: 0;
            background: linear-gradient(135deg, #7c3aed, var(--primary-color));
            z-index: -1;
            transition: opacity 0.3s ease;
            opacity: 0;
        }
        .btn-primary:hover::before { opacity: 1; }
        .btn-primary:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 25px -5px rgba(99, 102, 241, 0.4);
        }

        /* Accordion / FAQ */
        .faq-item { overflow: hidden; transition: all 0.3s ease; }
        .faq-summary {
            display: flex; justify-content: space-between; align-items: center;
            font-weight: 700; cursor: pointer; padding: 20px 24px; color: #1e293b;
            user-select: none; list-style: none;
        }
        .faq-summary::-webkit-details-marker { display: none; }
        .faq-summary::marker { display: none; content: ''; }
        .faq-chevron { transition: transform 0.3s ease; flex-shrink: 0; margin-left: 12px; }
        details[open] .faq-chevron { transform: rotate(180deg); }
        .faq-content {
            padding: 0 24px 20px 24px; color: #475569; line-height: 1.7;
            animation: faqSlideDown 0.3s ease;
        }
        @keyframes faqSlideDown {
            from { opacity: 0; transform: translateY(-8px); }
            to { opacity: 1; transform: translateY(0); }
        }

        /* Section scroll margin for fixed nav */
        section[id] { scroll-margin-top: 72px; }

        /* Unique background effects */
        ${bgEffects}

        /* 3D Card Hover Effects */
        .service-card-3d {
            transition: all 0.5s cubic-bezier(0.23, 1, 0.32, 1);
            transform-style: preserve-3d;
            perspective: 1000px;
            position: relative;
            overflow: hidden;
        }
        .service-card-3d::before {
            content: '';
            position: absolute;
            inset: -2px;
            border-radius: inherit;
            background: conic-gradient(from var(--card-angle, 0deg), transparent 40%, var(--primary-color) 50%, transparent 60%);
            z-index: -1;
            opacity: 0;
            transition: opacity 0.4s ease;
        }
        .service-card-3d::after {
            content: '';
            position: absolute;
            inset: 2px;
            border-radius: inherit;
            background: inherit;
            z-index: -1;
        }
        .service-card-3d:hover::before,
        .service-card-3d.touch-active::before {
            opacity: 1;
            animation: cardGlider 2.5s linear infinite;
        }
        @keyframes cardGlider {
            0% { --card-angle: 0deg; }
            100% { --card-angle: 360deg; }
        }
        @property --card-angle {
            syntax: '<angle>';
            initial-value: 0deg;
            inherits: false;
        }
        .service-card-3d:hover,
        .service-card-3d.touch-active {
            transform: translateY(-10px) rotateX(4deg) rotateY(4deg);
            box-shadow: 0 20px 40px -10px rgba(0,0,0,0.15), 0 0 30px 4px var(--primary-color);
            border-color: transparent;
        }
        .service-card-3d:hover .icon-container,
        .service-card-3d.touch-active .icon-container {
            transform: translateZ(20px);
            filter: drop-shadow(0 0 8px var(--primary-color));
        }

        /* Animated Hero Gradient — cycles colors smoothly */
        @keyframes heroColorCycle {
            0%   { filter: hue-rotate(0deg); }
            25%  { filter: hue-rotate(45deg); }
            50%  { filter: hue-rotate(90deg); }
            75%  { filter: hue-rotate(45deg); }
            100% { filter: hue-rotate(0deg); }
        }
        .hero-animated-gradient {
            animation: heroColorCycle 6s ease-in-out infinite;
        }

        .glass-panel-refined {
            background: rgba(255, 255, 255, 0.03);
            backdrop-filter: blur(16px);
            -webkit-backdrop-filter: blur(16px);
            border: 1px solid rgba(255, 255, 255, 0.08);
        }
    </style>
</head>
<body class="bg-effect text-slate-800 antialiased selection:bg-indigo-500 selection:text-white pb-0">

    <!-- Sticky Navbar -->
    <nav class="site-nav" data-no-edit="true">
        <div class="nav-inner">
            <a href="#home" class="nav-brand">${displayName}</a>
            <button class="nav-hamburger" onclick="document.querySelector('.nav-links').classList.toggle('open')" aria-label="Menu">
                <i class="fas fa-bars"></i>
            </button>
            <div class="nav-links">
                ${navHTML}
            </div>
        </div>
    </nav>

    <!-- Hero Section -->
    <header id="home" class="hero-animated-gradient text-white min-h-[85vh] flex items-center pt-28 pb-20 px-4 overflow-hidden relative" style="background: linear-gradient(${seed % 360}deg, var(--primary-color), #6366f1, #a855f7, #4f46e5);">
        <!-- 3D Hero Background -->
        <div id="hero-3d-container" class="absolute inset-0 z-0 pointer-events-none opacity-70">
            <canvas id="hero-3d-canvas" class="w-full h-full"></canvas>
        </div>
        
        <div class="container mx-auto max-w-4xl relative z-10 text-center px-2">
            <div class="glass-panel-refined rounded-[2rem] p-6 sm:p-10 md:p-14 animate-fade-in-up" style="max-width: 95vw;">
                <div class="inline-block mb-4 px-3 py-1 rounded-full border border-white/15 bg-white/5 text-white text-[11px] sm:text-sm font-semibold tracking-wide uppercase shadow-sm">
                    ${designation ? designation : tl.professionalServices}
                </div>
                <h1 class="text-2xl sm:text-4xl md:text-6xl lg:text-7xl font-extrabold mb-4 sm:mb-6 tracking-tight text-white drop-shadow-md leading-tight" style="word-break: break-word; overflow-wrap: break-word;">
                    ${displayName}
                </h1>
                <p class="text-sm sm:text-xl md:text-2xl text-slate-200 mb-6 sm:mb-10 font-light max-w-3xl mx-auto leading-relaxed">
                    ${displayBusiness}
                    ${tagline ? `<br><span class="text-xs sm:text-lg opacity-90 italic mt-2 block font-medium">"${tagline}"</span>` : ''}
                </p>
                <div class="flex flex-col sm:flex-row items-center justify-center gap-3 sm:gap-4">
                    <a href="#contact" class="btn-primary text-white px-6 sm:px-8 py-3 sm:py-4 rounded-full font-semibold w-full sm:w-auto flex items-center justify-center gap-2 text-sm sm:text-base"><i class="fas fa-phone-alt"></i> ${tl.getInTouch}</a>
                    ${services && services.length > 0 ? `<a href="#services" class="bg-white/10 hover:bg-white/20 border border-white/20 backdrop-blur-md text-white px-6 sm:px-8 py-3 sm:py-4 rounded-full font-semibold transition-all w-full sm:w-auto flex items-center justify-center gap-2 text-sm sm:text-base"><i class="fas fa-briefcase"></i> ${tl.servicesNav}</a>` : ''}
                </div>
            </div>
        </div>
        
        <!-- Beautiful bottom divider -->
        <div class="absolute bottom-0 left-0 right-0 h-16 bg-gradient-to-b from-transparent to-[#f8fafc]"></div>
    </header>

    <!-- Contact Info Grid -->
    <section id="contact" class="max-w-6xl mx-auto px-6 -mt-16 md:-mt-20 relative z-20 mb-20 animate-fade-in-up delay-100">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
            ${phone ? `
            <a href="${phoneLink}" class="bento-card p-8 rounded-[2rem] shadow-lg flex flex-col items-center text-center group">
                <div class="w-16 h-16 rounded-2xl flex items-center justify-center mb-6 text-2xl group-hover:scale-110 transition-transform duration-300 relative" style="color: var(--primary-color);"><i class="fas fa-phone-alt"></i></div>
                <h3 class="font-bold text-slate-900 text-xl mb-2">${tl.callUs}</h3>
                <p class="text-slate-500 font-medium">${phone}</p>
            </a>` : ''}
            
            ${email ? `
            <a href="${emailLink}" class="bento-card p-8 rounded-[2rem] shadow-lg flex flex-col items-center text-center group">
                <div class="w-16 h-16 rounded-2xl flex items-center justify-center mb-6 text-2xl group-hover:scale-110 transition-transform duration-300 relative" style="color: var(--primary-color);"><i class="fas fa-envelope-open-text"></i></div>
                <h3 class="font-bold text-slate-900 text-xl mb-2">${tl.emailUs}</h3>
                <p class="text-slate-500 font-medium">${email}</p>
            </a>` : ''}
            
            ${address ? `
            <div class="bento-card p-8 rounded-[2rem] shadow-lg flex flex-col items-center text-center group">
                <div class="w-16 h-16 rounded-2xl flex items-center justify-center mb-6 text-2xl group-hover:scale-110 transition-transform duration-300 relative" style="color: var(--primary-color);"><i class="fas fa-map-marked-alt"></i></div>
                <h3 class="font-bold text-slate-900 text-xl mb-2">${tl.location}</h3>
                <p class="text-slate-500 font-medium">${address}</p>
            </div>` : `
            <div class="bento-card p-8 rounded-[2rem] shadow-lg flex flex-col items-center text-center group">
                <div class="w-16 h-16 rounded-2xl flex items-center justify-center mb-6 text-2xl group-hover:scale-110 transition-transform duration-300 relative" style="color: var(--primary-color);"><i class="fas fa-star"></i></div>
                <h3 class="font-bold text-slate-900 text-xl mb-2">${tl.premiumQuality}</h3>
                <p class="text-slate-500 font-medium">${tl.guaranteedExp}</p>
            </div>
            `}
        </div>
    </section>

    <!-- About Section -->
    ${about ? `
    <section id="about" class="py-16 sm:py-20 md:py-24 bg-[#f8fafc] animate-fade-in-up delay-100 overflow-hidden">
        <div class="container mx-auto px-4 sm:px-6 max-w-6xl">
            <div class="flex flex-row items-stretch gap-4 sm:gap-8 lg:gap-16">
                <div class="w-1/2 flex flex-col justify-center">
                    <span class="font-bold uppercase tracking-wider text-[10px] sm:text-xs mb-2 sm:mb-4 block" style="color: var(--primary-color);">${tl.aboutUs}</span>
                    <h2 class="text-lg sm:text-3xl lg:text-5xl font-extrabold text-slate-900 mb-3 sm:mb-6 leading-tight">${tl.aboutUs}</h2>
                    <p class="text-[11px] sm:text-base lg:text-xl text-slate-700 leading-relaxed font-medium">"${about}"</p>
                </div>
                <div class="w-1/2 flex items-center justify-center">
                    <div id="about-3d-wrap" class="w-full h-[180px] sm:h-[300px] lg:h-[400px] relative">
                        <canvas id="about-3d-canvas" class="w-full h-full"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </section>
    ` : ''}

    <!-- Services Section -->
    ${services && services.length > 0 ? `
    <section id="services" class="py-24 bg-white relative overflow-hidden">
        <div class="absolute top-0 left-0 w-full h-px bg-gradient-to-r from-transparent via-slate-200 to-transparent"></div>
        <div class="container mx-auto px-6 max-w-6xl relative z-10 animate-fade-in-up delay-200">
            <div class="text-center mb-16 md:mb-20">
                <span class="font-bold uppercase tracking-wider text-sm mb-3 block" style="color: var(--primary-color);">${tl.whatWeDo}</span>
                <h2 class="text-4xl md:text-5xl font-extrabold text-slate-900 mb-6 tracking-tight">${tl.expertise}</h2>
                <div class="w-20 h-1.5 mx-auto rounded-full" style="background: linear-gradient(90deg, var(--primary-color), #a855f7);"></div>
            </div>
            
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                ${services.map(s => `
                <div class="service-card-3d group bg-slate-50 hover:bg-white p-8 rounded-3xl border border-slate-100 transition-all duration-300 relative overflow-hidden">
                    <div class="relative z-10">
                        <div class="icon-container w-12 h-12 bg-white rounded-xl shadow-sm border border-slate-100 flex items-center justify-center mb-6 transition-transform duration-500">
                            <i class="fas fa-check" style="color: var(--primary-color);"></i>
                        </div>
                        <h4 class="text-xl font-bold text-slate-800 leading-snug tracking-tight">${s}</h4>
                    </div>
                </div>
                `).join('')}
            </div>
        </div>
    </section>
    ` : ''}

    <!-- Image Gallery Section -->
    ${images && images.length > 0 ? `
    <section id="gallery" class="py-16 bg-[#f8fafc] animate-fade-in-up delay-200">
        <div class="container mx-auto px-6 max-w-6xl">
            <div class="text-center mb-12">
                <h2 class="text-3xl font-extrabold text-slate-900 tracking-tight">${tl.galleryTitle}</h2>
                <div class="w-12 h-1 mt-4 mx-auto rounded-full" style="background-color: var(--primary-color);"></div>
            </div>
            <style>
                .hide-scrollbar::-webkit-scrollbar { display: none; }
                .hide-scrollbar { -ms-overflow-style: none; scrollbar-width: none; }
            </style>
            <div class="flex overflow-x-auto snap-x snap-mandatory gap-6 pb-8 hide-scrollbar px-4 -mx-4">
                ${images.map((imgKeyword, idx) => `
                <div class="flex-none w-[85vw] sm:w-[320px] snap-center group relative rounded-2xl overflow-hidden aspect-[4/3] shadow-xl hover:shadow-2xl transition-all duration-500 transform hover:-translate-y-2">
                    <!-- Dynamic Color Gradient Picture -->
                    <div class="w-full h-full" style="background: linear-gradient(${135 + idx * 55}deg, var(--primary-color), #fff); filter: hue-rotate(${idx * 45}deg) saturate(1.5);"></div>
                    <div class="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent group-hover:from-black/90 transition-all duration-500"></div>
                    
                    <!-- Decorative Element -->
                    <div class="absolute top-4 right-4 w-12 h-12 rounded-full border border-white/20 flex items-center justify-center text-white/50 backdrop-blur-md group-hover:rotate-45 transition-transform duration-500">
                        <i class="fas fa-star"></i>
                    </div>

                    <!-- Centered Content on Hover -->
                    <div class="absolute inset-0 flex items-center justify-center translate-y-8 opacity-0 group-hover:translate-y-0 group-hover:opacity-100 transition-all duration-500 z-10 px-6 text-center">
                         <span class="text-white text-lg font-bold tracking-wider border-2 border-white/50 px-6 py-3 rounded-full backdrop-blur-md bg-black/20 shadow-lg">${imgKeyword}</span>
                    </div>

                    <!-- Default Bottom Title -->
                    <div class="absolute bottom-6 left-6 right-6 text-white group-hover:opacity-0 transition-opacity duration-300">
                        <div class="w-8 h-1 bg-white mb-3 rounded-full bg-opacity-70"></div>
                        <div class="text-2xl font-bold drop-shadow-md capitalize truncate">${imgKeyword}</div>
                    </div>
                </div>
                `).join('')}
            </div>
        </div>
    </section>
    ` : ''}

    <!-- Testimonials Section -->
    ${testimonials && testimonials.length > 0 ? `
    <section class="py-24 bg-white animate-fade-in-up delay-300">
        <div class="container mx-auto px-6 max-w-5xl">
            <div class="text-center mb-16">
                <h2 class="text-4xl font-extrabold text-slate-900 tracking-tight">${tl.testimonialsTitle}</h2>
                <div class="w-16 h-1 mt-4 mx-auto rounded-full" style="background-color: var(--primary-color);"></div>
            </div>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
                ${testimonials.map(t => `
                <div class="bg-slate-50 p-8 rounded-3xl border border-slate-100 flex flex-col items-center text-center shadow-sm">
                    <div class="text-yellow-400 text-lg mb-4">
                        <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
                    </div>
                    <p class="text-slate-600 italic mb-6 flex-1">"${t.text}"</p>
                    <div class="flex items-center gap-3">
                        <img src="https://ui-avatars.com/api/?name=${encodeURIComponent(t.name)}&background=random" alt="${t.name}" class="w-10 h-10 rounded-full shadow-sm" loading="lazy" />
                        <h5 class="font-bold text-slate-800">${t.name}</h5>
                    </div>
                </div>
                `).join('')}
            </div>
        </div>
    </section>
    ` : ''}

    <!-- FAQ Accordion -->
    ${faqs && faqs.length > 0 ? `
    <section class="py-24 bg-[#f8fafc] animate-fade-in-up delay-300">
        <div class="container mx-auto px-6 max-w-3xl">
            <div class="text-center mb-12">
                <h2 class="text-4xl font-extrabold text-slate-900 tracking-tight">${tl.faqTitle}</h2>
            </div>
            <div class="space-y-4">
                ${faqs.map((faq, index) => `
                <details class="faq-item group bg-white rounded-2xl shadow-sm border border-slate-200 transition-all duration-300 hover:shadow-md" ${index === 0 ? 'open' : ''}>
                    <summary class="faq-summary">
                        <span class="pr-4">${faq.question}</span>
                        <span class="faq-chevron">
                            <i class="fas fa-chevron-down text-slate-400"></i>
                        </span>
                    </summary>
                    <div class="faq-content">
                        ${faq.answer}
                    </div>
                </details>
                `).join('')}
            </div>
        </div>
    </section>
    ` : ''}

    <!-- Footer -->
    <footer class="bg-[#020617] text-slate-400 py-16 relative overflow-hidden text-center border-t border-slate-800">
        <div class="absolute inset-0 bg-gradient-to-b from-[#0f172a] to-[#020617] opacity-50"></div>
        <div class="container mx-auto px-6 relative z-10 animate-fade-in-up delay-300">
            <h2 class="text-3xl font-bold text-white mb-3" style="color: var(--primary-color);">${displayName}</h2>
            <p class="mb-8 text-slate-500 text-lg">${displayBusiness}</p>
            <div class="w-full max-w-md mx-auto h-px bg-slate-800 mb-8"></div>
            <p class="mb-6 font-medium tracking-wide" data-no-edit="true">&copy; ${new Date().getFullYear()} ${displayName}. ${tl.allRights}.</p>
            <a href="https://yuktha-52jo1yac2-dharshinipriyaa426-3149s-projects.vercel.app" data-no-edit="true" class="inline-flex items-center gap-3 text-sm hover:text-white transition-colors bg-slate-900 border border-slate-800 px-5 py-2.5 rounded-full shadow-lg">
                <span class="font-semibold tracking-wide">${tl.generatedBy}</span>
            </a>
        </div>
    </footer>

    <!-- Floating WhatsApp Button -->
    ${phone ? `
    <a href="${waLink}" target="_blank" aria-label="Chat on WhatsApp" class="fixed bottom-6 right-6 bg-[#25D366] text-white w-16 h-16 rounded-full flex items-center justify-center text-3xl shadow-[0_10px_25px_-5px_rgba(37,211,102,0.5)] hover:bg-[#128C7E] transition-all hover:scale-110 hover:shadow-[0_15px_35px_-5px_rgba(37,211,102,0.6)] z-50 animate-fade-in-up delay-300">
        <i class="fab fa-whatsapp"></i>
    </a>` : ''}


    <!-- Three.js for 3D Components -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"><\/script>
    <script>
        (function() {
            const seed = ${seed};
            
            function createScene(canvasId, geometryType) {
                const canvas = document.getElementById(canvasId);
                if (!canvas) return;

                const parent = canvas.parentElement;
                const scene = new THREE.Scene();
                const camera = new THREE.PerspectiveCamera(75, parent.clientWidth / parent.clientHeight, 0.1, 1000);
                const renderer = new THREE.WebGLRenderer({ canvas, alpha: true, antialias: true });
                renderer.setPixelRatio(window.devicePixelRatio);
                renderer.setSize(parent.clientWidth, parent.clientHeight);

                let geometry;
                switch(geometryType) {
                    case 0: geometry = new THREE.TorusKnotGeometry(10, 3, 100, 16); break;
                    case 1: geometry = new THREE.IcosahedronGeometry(12, 1); break;
                    case 2: geometry = new THREE.OctahedronGeometry(12, 2); break;
                    case 3: geometry = new THREE.SphereGeometry(12, 32, 32); break;
                    default: geometry = new THREE.TorusKnotGeometry(10, 3, 100, 16);
                }

                const material = new THREE.MeshNormalMaterial({ 
                    wireframe: true,
                    transparent: true,
                    opacity: 0.8
                });
                const mesh = new THREE.Mesh(geometry, material);
                scene.add(mesh);

                // Add a ring if it's the hero or special
                if (canvasId === 'hero-3d-canvas') {
                    const ringGeo = new THREE.TorusGeometry(18, 0.5, 16, 100);
                    const ringMat = new THREE.MeshNormalMaterial({ transparent: true, opacity: 0.4 });
                    const ring = new THREE.Mesh(ringGeo, ringMat);
                    ring.rotation.x = Math.PI / 2;
                    scene.add(ring);
                    mesh.userData.ring = ring;
                }

                camera.position.z = 35;

                let mouseX = 0, mouseY = 0;
                let isActive = false;
                
                // Find the closest section/header ancestor
                const section = parent.closest('section, header') || parent;
                
                section.addEventListener('mouseenter', () => { isActive = true; });
                section.addEventListener('mouseleave', () => { isActive = false; mouseX = 0; mouseY = 0; });
                section.addEventListener('mousemove', (e) => {
                    if (!isActive) return;
                    const rect = canvas.getBoundingClientRect();
                    mouseX = ((e.clientX - rect.left) / rect.width - 0.5) * 2;
                    mouseY = ((e.clientY - rect.top) / rect.height - 0.5) * 2;
                });
                section.addEventListener('touchmove', (e) => {
                    const touch = e.touches[0];
                    const rect = canvas.getBoundingClientRect();
                    mouseX = ((touch.clientX - rect.left) / rect.width - 0.5) * 2;
                    mouseY = ((touch.clientY - rect.top) / rect.height - 0.5) * 2;
                }, { passive: true });
                section.addEventListener('touchend', () => { mouseX = 0; mouseY = 0; }, { passive: true });

                function animate() {
                    requestAnimationFrame(animate);
                    mesh.rotation.x += 0.005;
                    mesh.rotation.y += 0.005;
                    
                    if (mesh.userData.ring) {
                        mesh.userData.ring.rotation.z += 0.002;
                        mesh.userData.ring.rotation.x += mouseX * 0.01;
                    }
                    
                    mesh.position.x += (mouseX * 5 - mesh.position.x) * 0.05;
                    mesh.position.y += (-mouseY * 5 - mesh.position.y) * 0.05;

                    renderer.render(scene, camera);
                }

                window.addEventListener('resize', () => {
                    camera.aspect = parent.clientWidth / parent.clientHeight;
                    camera.updateProjectionMatrix();
                    renderer.setSize(parent.clientWidth, parent.clientHeight);
                });

                animate();
            }

            createScene('hero-3d-canvas', 0); // Always use TorusKnot for Hero
            createScene('about-3d-canvas', ${uniqueSeed % 4});
        })();

        window.addEventListener('scroll', function() {
            const nav = document.querySelector('.site-nav');
            if (nav) nav.classList.toggle('scrolled', window.scrollY > 50);
        });
        // Close mobile menu on link click
        document.querySelectorAll('.nav-link').forEach(l => l.addEventListener('click', () => {
            document.querySelector('.nav-links')?.classList.remove('open');
        }));

        // Touch sensitivity for service cards (mobile-friendly)
        document.querySelectorAll('.service-card-3d').forEach(card => {
            card.addEventListener('touchstart', function(e) {
                this.classList.add('touch-active');
            }, { passive: true });
            card.addEventListener('touchend', function(e) {
                setTimeout(() => this.classList.remove('touch-active'), 1500);
            }, { passive: true });
        });

        // Touch sensitivity for 3D canvas (About section)
        const aboutWrap = document.getElementById('about-3d-wrap');
        if (aboutWrap) {
            aboutWrap.addEventListener('touchmove', function(e) {
                const touch = e.touches[0];
                const rect = this.getBoundingClientRect();
                const mouseEvent = new MouseEvent('mousemove', {
                    clientX: touch.clientX,
                    clientY: touch.clientY
                });
                document.dispatchEvent(mouseEvent);
            }, { passive: true });
        }

        // Auto-scroll gradient carousel
        const carousel = document.querySelector('.snap-x');
        if (carousel) {
            let scrollPos = 0;
            setInterval(() => {
                const maxScroll = carousel.scrollWidth - carousel.clientWidth;
                scrollPos += carousel.clientWidth > 400 ? 344 : window.innerWidth * 0.85; // card width + gap
                if (scrollPos > maxScroll + 10) scrollPos = 0;
                carousel.scrollTo({ left: scrollPos, behavior: 'smooth' });
            }, 2000);
        }
    </script>

</body>
</html>`;
}
