export function buildModernTemplate(data, isPreview, langName) {
  const { name, business, designation, phone, email, address, services, tagline, about, faqs, testimonials, theme, images } = data;

  const translations = {
    "English": {
      myBusiness: "My Business",
      professionalServices: "Professional Services",
      callUs: "Call Us",
      emailUs: "Email Us",
      location: "Location",
      premiumQuality: "Premium Quality",
      guaranteedExp: "Guaranteed Experience",
      whatWeDo: "What We Do",
      expertise: "Expertise & Services",
      generatedBy: "Generated by Yuktha",
      getInTouch: "Get in Touch",
      allRights: "All Rights Reserved",
      aboutUs: "About Us",
      faqTitle: "Frequently Asked Questions",
      testimonialsTitle: "What Our Clients Say",
      galleryTitle: "Our Work"
    },
    "Tamil": {
      myBusiness: "என் வணிகம்",
      professionalServices: "தொழில்முறை சேவைகள்",
      callUs: "அழைக்க",
      emailUs: "மின்னஞ்சல்",
      location: "இருப்பிடம்",
      premiumQuality: "உயர்தரமான தரம்",
      guaranteedExp: "உத்தரவாதமான அனுபவம்",
      whatWeDo: "நாங்கள் செய்வது",
      expertise: "நிபுணத்துவம் மற்றும் சேவைகள்",
      generatedBy: "யுக்தா மூலம் உருவாக்கப்பட்டது",
      getInTouch: "தொடர்புகொள்ளுங்கள்",
      allRights: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை",
      aboutUs: "எங்களை பற்றி",
      faqTitle: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
      testimonialsTitle: "வாடிக்கையாளர் மதிப்புரைகள்",
      galleryTitle: "எங்கள் படைப்புகள்"
    },
    "Hindi": {
      myBusiness: "मेरा व्यापार",
      professionalServices: "पेशेवर सेवाएं",
      callUs: "हमें कॉल करें",
      emailUs: "ईमेल करें",
      location: "स्थान",
      premiumQuality: "प्रीमियम गुणवत्ता",
      guaranteedExp: "गारंटीशुदा अनुभव",
      whatWeDo: "हम क्या करते हैं",
      expertise: "विशेषज्ञता और सेवाएं",
      generatedBy: "युक्ता द्वारा निर्मित",
      getInTouch: "संपर्क करें",
      allRights: "सर्वाधिकार सुरक्षित",
      aboutUs: "हमारे बारे में",
      faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
      testimonialsTitle: "ग्राहक समीक्षा",
      galleryTitle: "हमारा काम"
    },
    "Telugu": {
      myBusiness: "నా వ్యాపారం",
      professionalServices: "వృత్తిపరమైన సేవలు",
      callUs: "మాకు కాల్ చేయండి",
      emailUs: "ఈమెయిల్ చేయండి",
      location: "స్థానం",
      premiumQuality: "ప్రీమియం నాణ్యత",
      guaranteedExp: "హామీ బడిన అనుభవం",
      whatWeDo: "మేము ఏమి చేస్తాము",
      expertise: "నైపుణ్యం మరియు సేవలు",
      generatedBy: "యుక్త ద్వారా సృష్టించబడింది",
      getInTouch: "మమ్మల్ని సంప్రదించండి",
      allRights: "సర్వ హక్కులూ ప్రత్యేకించబడినవి",
      aboutUs: "మా గురించి",
      faqTitle: "తరచుగా అడిగే ప్రశ్నలు",
      testimonialsTitle: "కస్టమర్ అభిప్రాయాలు",
      galleryTitle: "మా పని"
    },
    "Malayalam": {
      myBusiness: "എന്റെ ബിസിനസ്സ്",
      professionalServices: "പ്രൊഫഷണൽ സേവനങ്ങൾ",
      callUs: "ഞങ്ങളെ വിളിക്കുക",
      emailUs: "ഇമെയിൽ ചെയ്യുക",
      location: "സ്ഥാനം",
      premiumQuality: "പ്രീമിയം നിലവാരം",
      guaranteedExp: "ഉറപ്പായ അനുഭവം",
      whatWeDo: "ഞങ്ങൾ ചെയ്യുന്നത്",
      expertise: "വൈദഗ്ധ്യവും സേവനങ്ങളും",
      generatedBy: "യുക്ത നിർമ്മിച്ചത്",
      getInTouch: "ബന്ധപ്പെടുക",
      allRights: "എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം",
      aboutUs: "ഞങ്ങളെക്കുറിച്ച്",
      faqTitle: "പതിവായി ചോദിക്കുന്ന ചോദ്യങ്ങൾ",
      testimonialsTitle: "ഉപഭോക്തൃ അഭിപ്രായങ്ങൾ",
      galleryTitle: "ഞങ്ങളുടെ പ്രവർത്തനം"
    },
    "Kannada": {
      myBusiness: "ನನ್ನ ವ್ಯಾಪಾರ",
      professionalServices: "ವೃತ್ತಿಪರ ಸೇವೆಗಳು",
      callUs: "ನಮ್ಮನ್ನು ಕರೆ ಮಾಡಿ",
      emailUs: "ಇಮೇಲ್ ಮಾಡಿ",
      location: "ಸ್ಥಳ",
      premiumQuality: "ಉತ್ತಮ ಗುಣಮಟ್ಟ",
      guaranteedExp: "ಖಾತರಿಯ ಅನುಭವ",
      whatWeDo: "ನಾವು ಮಾಡುವುದು",
      expertise: "ಪರಿಣತಿ ಮತ್ತು ಸೇವೆಗಳು",
      generatedBy: "ಯುಕ್ತಾ ಮೂಲಕ ರಚಿಸಲಾಗಿದೆ",
      getInTouch: "ಸಂಪರ್ಕಿಸಿ",
      allRights: "ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ",
      aboutUs: "ನಮ್ಮ ಬಗ್ಗೆ",
      faqTitle: "ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
      testimonialsTitle: "ಗ್ರಾಹಕರ ವಿಮರ್ಶೆಗಳು",
      galleryTitle: "ನಮ್ಮ ಕೆಲಸ"
    },
    "Bengali": {
      myBusiness: "আমার ব্যবসা",
      professionalServices: "পেশাদার পরিষেবা",
      callUs: "আমাদের কল করুন",
      emailUs: "ইমেল করুন",
      location: "অবস্থান",
      premiumQuality: "প্রিমিয়াম গুণমান",
      guaranteedExp: "নিশ্চিত অভিজ্ঞতা",
      whatWeDo: "আমরা যা করি",
      expertise: "দক্ষতা এবং পরিষেবা",
      generatedBy: "যুক্তা দ্বারা তৈরি",
      getInTouch: "যোগাযোগ করুন",
      allRights: "সমস্ত অধিকার সংরক্ষিত",
      aboutUs: "আমাদের সম্পর্কে",
      faqTitle: "সাধারণ প্রশ্ন জিজ্ঞাসা",
      testimonialsTitle: "গ্রাহক পর্যালোচনা",
      galleryTitle: "আমাদের কাজ"
    }
  };

  const tl = translations[isPreview ? langName : "English"] || translations["English"];

  // Add fallbacks
  const displayName = name || business || tl.myBusiness;
  const displayBusiness = business || tl.professionalServices;
  const primaryBrandColor = theme?.primaryColor || '#4f46e5';
  
  const phoneLink = phone ? `tel:${phone.replace(/[^0-9+]/g, '')}` : "#";
  const emailLink = email ? `mailto:${email}` : "#";
  const waLink = phone ? `https://wa.me/${phone.replace(/[^0-9+]/g, '')}` : "#";

  return `<!DOCTYPE html>
<html lang="${isPreview ? 'en' : 'en'}" class="scroll-smooth">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${displayName} - ${displayBusiness}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        :root {
            --primary-color: ${primaryBrandColor};
        }
    
        body { font-family: 'Plus Jakarta Sans', sans-serif; background-color: #f8fafc; overflow-x: hidden; }
        
        /* Dynamic Hero Background */
        .hero-gradient {
            background: linear-gradient(-45deg, #020617, #0f172a, var(--primary-color), #0f172a);
            background-size: 400% 400%;
            animation: gradientBG 15s ease infinite;
            position: relative;
        }
        @keyframes gradientBG {
            0% { background-position: 0% 50%; }
            50% { background-position: 100% 50%; }
            100% { background-position: 0% 50%; }
        }
        
        /* Premium Premium Glassmorphism */
        .glass-panel {
            background: rgba(255, 255, 255, 0.03);
            backdrop-filter: blur(16px);
            -webkit-backdrop-filter: blur(16px);
            border: 1px solid rgba(255, 255, 255, 0.05);
            box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
        }
        
        .bento-card {
            background: #ffffff;
            transition: all 0.4s cubic-bezier(0.16, 1, 0.3, 1);
            border: 1px solid rgba(226, 232, 240, 0.8);
        }
        .bento-card:hover {
            transform: translateY(-5px) scale(1.01);
            box-shadow: 0 20px 40px -10px rgba(79, 70, 229, 0.15);
            border-color: var(--primary-color);
        }

        .icon-gradient {
            background: linear-gradient(135deg, var(--primary-color), #a855f7);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        /* Subtle Reveal Animations */
        .animate-fade-in-up {
            animation: fadeInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) both;
        }
        .delay-100 { animation-delay: 0.1s; }
        .delay-200 { animation-delay: 0.2s; }
        .delay-300 { animation-delay: 0.3s; }
        @keyframes fadeInUp {
            from { opacity: 0; transform: translateY(30px); }
            to { opacity: 1; transform: translateY(0); }
        }

        /* Dynamic primary button */
        .btn-primary {
            background: linear-gradient(135deg, var(--primary-color), #7c3aed);
            transition: all 0.3s ease;
            position: relative;
            overflow: hidden;
            z-index: 1;
        }
        .btn-primary::before {
            content: '';
            position: absolute;
            top: 0; left: 0; right: 0; bottom: 0;
            background: linear-gradient(135deg, #7c3aed, var(--primary-color));
            z-index: -1;
            transition: opacity 0.3s ease;
            opacity: 0;
        }
        .btn-primary:hover::before { opacity: 1; }
        .btn-primary:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 25px -5px rgba(99, 102, 241, 0.4);
        }

        /* Custom Accordion */
        details > summary { list-style-type: none; }
        details > summary::-webkit-details-marker { display: none; }
    </style>
</head>
<body class="text-slate-800 antialiased selection:bg-indigo-500 selection:text-white pb-0">

    <!-- Hero Section -->
    <header class="hero-gradient text-white pt-28 pb-32 md:pt-40 md:pb-48 px-6">
        <div class="container mx-auto max-w-5xl relative z-10">
            <div class="glass-panel rounded-3xl p-10 md:p-16 text-center animate-fade-in-up">
                <div class="inline-block mb-4 px-4 py-1.5 rounded-full border border-white/20 bg-white/10 text-white text-sm font-semibold tracking-wide uppercase shadow-sm">
                    ${designation ? designation : tl.professionalServices}
                </div>
                <h1 class="text-5xl md:text-7xl font-extrabold mb-6 tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-white via-indigo-50 to-indigo-200 drop-shadow-sm">
                    ${displayName}
                </h1>
                <p class="text-xl md:text-2xl text-slate-200 mb-10 font-light max-w-3xl mx-auto leading-relaxed">
                    ${displayBusiness}
                    ${tagline ? `<br><span class="text-lg opacity-90 italic mt-3 block font-medium">"${tagline}"</span>` : ''}
                </p>
                <div class="flex flex-col sm:flex-row items-center justify-center gap-4">
                    ${phone ? `<a href="${phoneLink}" class="btn-primary text-white px-8 py-4 rounded-full font-semibold w-full sm:w-auto flex items-center justify-center gap-3"><i class="fas fa-phone-alt"></i> ${tl.getInTouch}</a>` : ''}
                    ${email ? `<a href="${emailLink}" class="bg-white/10 hover:bg-white/20 border border-white/20 backdrop-blur-md text-white px-8 py-4 rounded-full font-semibold transition-all w-full sm:w-auto flex items-center justify-center gap-3"><i class="fas fa-envelope"></i> ${tl.emailUs}</a>` : ''}
                </div>
            </div>
        </div>
        
        <!-- Beautiful bottom divider -->
        <div class="absolute bottom-0 left-0 right-0 h-16 bg-gradient-to-b from-transparent to-[#f8fafc]"></div>
    </header>

    <!-- Info & Contact Grid -->
    <section class="max-w-6xl mx-auto px-6 -mt-16 md:-mt-24 relative z-20 mb-20 animate-fade-in-up delay-100">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
            ${phone ? `
            <a href="${phoneLink}" class="bento-card p-8 rounded-[2rem] shadow-lg flex flex-col items-center text-center group">
                <div class="w-16 h-16 rounded-2xl flex items-center justify-center mb-6 text-2xl group-hover:scale-110 transition-transform duration-300 shadow-sm border" style="background-color: var(--primary-color); opacity: 0.1; position: absolute;"></div>
                <div class="w-16 h-16 rounded-2xl flex items-center justify-center mb-6 text-2xl group-hover:scale-110 transition-transform duration-300 relative" style="color: var(--primary-color);"><i class="fas fa-phone-alt"></i></div>
                <h3 class="font-bold text-slate-900 text-xl mb-2">${tl.callUs}</h3>
                <p class="text-slate-500 font-medium">${phone}</p>
            </a>` : ''}
            
            ${email ? `
            <a href="${emailLink}" class="bento-card p-8 rounded-[2rem] shadow-lg flex flex-col items-center text-center group">
                <div class="w-16 h-16 rounded-2xl flex items-center justify-center mb-6 text-2xl group-hover:scale-110 transition-transform duration-300 shadow-sm border" style="background-color: var(--primary-color); opacity: 0.1; position: absolute;"></div>
                <div class="w-16 h-16 rounded-2xl flex items-center justify-center mb-6 text-2xl group-hover:scale-110 transition-transform duration-300 relative" style="color: var(--primary-color);"><i class="fas fa-envelope-open-text"></i></div>
                <h3 class="font-bold text-slate-900 text-xl mb-2">${tl.emailUs}</h3>
                <p class="text-slate-500 font-medium">${email}</p>
            </a>` : ''}
            
            ${address ? `
            <div class="bento-card p-8 rounded-[2rem] shadow-lg flex flex-col items-center text-center group">
                <div class="w-16 h-16 rounded-2xl flex items-center justify-center mb-6 text-2xl group-hover:scale-110 transition-transform duration-300 shadow-sm border" style="background-color: var(--primary-color); opacity: 0.1; position: absolute;"></div>
                <div class="w-16 h-16 rounded-2xl flex items-center justify-center mb-6 text-2xl group-hover:scale-110 transition-transform duration-300 relative" style="color: var(--primary-color);"><i class="fas fa-map-marked-alt"></i></div>
                <h3 class="font-bold text-slate-900 text-xl mb-2">${tl.location}</h3>
                <p class="text-slate-500 font-medium">${address}</p>
            </div>` : `
            <div class="bento-card p-8 rounded-[2rem] shadow-lg flex flex-col items-center text-center group">
                <div class="w-16 h-16 rounded-2xl flex items-center justify-center mb-6 text-2xl group-hover:scale-110 transition-transform duration-300 shadow-sm border" style="background-color: var(--primary-color); opacity: 0.1; position: absolute;"></div>
                <div class="w-16 h-16 rounded-2xl flex items-center justify-center mb-6 text-2xl group-hover:scale-110 transition-transform duration-300 relative" style="color: var(--primary-color);"><i class="fas fa-star"></i></div>
                <h3 class="font-bold text-slate-900 text-xl mb-2">${tl.premiumQuality}</h3>
                <p class="text-slate-500 font-medium">${tl.guaranteedExp}</p>
            </div>
            `}
        </div>
    </section>

    <!-- About Section -->
    ${about ? `
    <section class="py-16 bg-[#f8fafc] animate-fade-in-up delay-100">
        <div class="container mx-auto px-6 max-w-4xl text-center">
            <span class="font-bold uppercase tracking-wider text-sm mb-3 block" style="color: var(--primary-color);">${tl.aboutUs}</span>
            <p class="text-xl md:text-2xl text-slate-700 leading-relaxed font-medium">"${about}"</p>
        </div>
    </section>
    ` : ''}

    <!-- Services Section -->
    ${services && services.length > 0 ? `
    <section class="py-24 bg-white relative overflow-hidden">
        <div class="absolute top-0 left-0 w-full h-px bg-gradient-to-r from-transparent via-slate-200 to-transparent"></div>
        <div class="container mx-auto px-6 max-w-6xl relative z-10 animate-fade-in-up delay-200">
            <div class="text-center mb-16 md:mb-20">
                <span class="font-bold uppercase tracking-wider text-sm mb-3 block" style="color: var(--primary-color);">${tl.whatWeDo}</span>
                <h2 class="text-4xl md:text-5xl font-extrabold text-slate-900 mb-6 tracking-tight">${tl.expertise}</h2>
                <div class="w-20 h-1.5 mx-auto rounded-full" style="background: linear-gradient(90deg, var(--primary-color), #a855f7);"></div>
            </div>
            
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                ${services.map(s => `
                <div class="group bg-slate-50 hover:bg-white p-8 rounded-3xl border border-slate-100 hover:shadow-2xl transition-all duration-300 relative overflow-hidden">
                    <div class="relative z-10">
                        <div class="w-12 h-12 bg-white rounded-xl shadow-sm border border-slate-100 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                            <i class="fas fa-check" style="color: var(--primary-color);"></i>
                        </div>
                        <h4 class="text-xl font-bold text-slate-800 leading-snug tracking-tight">${s}</h4>
                    </div>
                </div>
                `).join('')}
            </div>
        </div>
    </section>
    ` : ''}

    <!-- Image Gallery Section -->
    ${images && images.length > 0 ? `
    <section class="py-16 bg-[#f8fafc] animate-fade-in-up delay-200">
        <div class="container mx-auto px-6 max-w-6xl">
            <div class="text-center mb-12">
                <h2 class="text-3xl font-extrabold text-slate-900 tracking-tight">${tl.galleryTitle}</h2>
                <div class="w-12 h-1 mt-4 mx-auto rounded-full" style="background-color: var(--primary-color);"></div>
            </div>
            <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">
                ${images.map(imgKeyword => `
                <div class="group relative rounded-2xl overflow-hidden aspect-[4/3] shadow-md bg-slate-100">
                    <img src="https://source.unsplash.com/featured/800x600/?${encodeURIComponent(imgKeyword + ',professional')}" onerror="this.onerror=null; this.src='https://loremflickr.com/800/600/${encodeURIComponent(imgKeyword + ',professional')}';" alt="${imgKeyword}" class="w-full h-full object-cover transform group-hover:scale-110 transition-transform duration-700" loading="lazy" />
                    <div class="absolute inset-0 bg-black/20 group-hover:bg-black/0 transition-colors duration-500"></div>
                </div>
                `).join('')}
            </div>
        </div>
    </section>
    ` : ''}

    <!-- Testimonials Section -->
    ${testimonials && testimonials.length > 0 ? `
    <section class="py-24 bg-white animate-fade-in-up delay-300">
        <div class="container mx-auto px-6 max-w-5xl">
            <div class="text-center mb-16">
                <h2 class="text-4xl font-extrabold text-slate-900 tracking-tight">${tl.testimonialsTitle}</h2>
                <div class="w-16 h-1 mt-4 mx-auto rounded-full" style="background-color: var(--primary-color);"></div>
            </div>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
                ${testimonials.map(t => `
                <div class="bg-slate-50 p-8 rounded-3xl border border-slate-100 flex flex-col items-center text-center shadow-sm">
                    <div class="text-yellow-400 text-lg mb-4">
                        <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
                    </div>
                    <p class="text-slate-600 italic mb-6 flex-1">"${t.text}"</p>
                    <div class="flex items-center gap-3">
                        <img src="https://ui-avatars.com/api/?name=${encodeURIComponent(t.name)}&background=random" alt="${t.name}" class="w-10 h-10 rounded-full shadow-sm" loading="lazy" />
                        <h5 class="font-bold text-slate-800">${t.name}</h5>
                    </div>
                </div>
                `).join('')}
            </div>
        </div>
    </section>
    ` : ''}

    <!-- FAQ Accordion -->
    ${faqs && faqs.length > 0 ? `
    <section class="py-24 bg-[#f8fafc] animate-fade-in-up delay-300">
        <div class="container mx-auto px-6 max-w-3xl">
            <div class="text-center mb-12">
                <h2 class="text-4xl font-extrabold text-slate-900 tracking-tight">${tl.faqTitle}</h2>
            </div>
            <div class="space-y-4">
                ${faqs.map((faq, index) => `
                <details class="group bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden open:ring-2 open:ring-slate-100 transition-all duration-300" ${index === 0 ? 'open' : ''}>
                    <summary class="flex justify-between items-center font-bold cursor-pointer list-none p-6 text-slate-800">
                        <span>${faq.question}</span>
                        <span class="transition-transform group-open:rotate-180">
                            <i class="fas fa-chevron-down text-slate-400"></i>
                        </span>
                    </summary>
                    <div class="text-slate-600 px-6 pb-6 leading-relaxed">
                        ${faq.answer}
                    </div>
                </details>
                `).join('')}
            </div>
        </div>
    </section>
    ` : ''}

    <!-- Footer -->
    <footer class="bg-[#020617] text-slate-400 py-16 relative overflow-hidden text-center border-t border-slate-800">
        <div class="absolute inset-0 bg-gradient-to-b from-[#0f172a] to-[#020617] opacity-50"></div>
        <div class="container mx-auto px-6 relative z-10 animate-fade-in-up delay-300">
            <h2 class="text-3xl font-bold text-white mb-3" style="color: var(--primary-color);">${displayName}</h2>
            <p class="mb-8 text-slate-500 text-lg">${displayBusiness}</p>
            <div class="w-full max-w-md mx-auto h-px bg-slate-800 mb-8"></div>
            <p class="mb-6 font-medium tracking-wide">&copy; ${new Date().getFullYear()} ${tl.allRights}.</p>
            <a href="https://yuktha-52jo1yac2-dharshinipriyaa426-3149s-projects.vercel.app" data-no-edit="true" class="inline-flex items-center gap-3 text-sm hover:text-white transition-colors bg-slate-900 border border-slate-800 px-5 py-2.5 rounded-full shadow-lg">
                <span class="font-semibold tracking-wide">${tl.generatedBy}</span>
            </a>
        </div>
    </footer>

    <!-- Floating WhatsApp Button -->
    ${phone ? `
    <a href="${waLink}" target="_blank" aria-label="Chat on WhatsApp" class="fixed bottom-6 right-6 bg-[#25D366] text-white w-16 h-16 rounded-full flex items-center justify-center text-3xl shadow-[0_10px_25px_-5px_rgba(37,211,102,0.5)] hover:bg-[#128C7E] transition-all hover:scale-110 hover:shadow-[0_15px_35px_-5px_rgba(37,211,102,0.6)] z-50 animate-fade-in-up delay-300">
        <i class="fab fa-whatsapp"></i>
    </a>` : ''}

</body>
</html>`;
}
