@echo off
echo Running git remote...
git remote -v
echo Running git add...
git add .
echo Running git commit...
git commit -m "Pushing files to new repo"
echo Running git push...
git push -u origin main
